# Generated by Django 4.1.5 on 2024-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='joker.png.jpg', upload_to='media/'),
        ),
    ]
